# Executable names:
EXE = final
TEST = test

# Add all object files needed for compiling:
EXE_OBJ = main.o
OBJS = main.o BFSGraph.o shortestPath.o leastFlights.o mostPopular.o BFSGraph.o

# Use the cs225 makefile template:
include cs225/make/cs225.mk
